### ISSUE TITLE
Any plans to update this for Open API 3.0.x?

### ISSUE THREAD

**Issue by wordtracker** [ErikWittern/swagger-snippet#16]
This is definitely an improvement on swagger-codegen and openapi-generator however it only seem to work for Swagger 2.0.x. Any plans to update this for Open API 3.0.x?

**Comment by ErikWittern** [comment]
@wordtracker I have (shamefully) neglected this repository for a while. I will try to update a few things and this is a good idea indeed. I would, of course, also be happy to accept a PR to this regard.

**Comment by ErikWittern** [comment]
@wordtracker This PR from @gugu just provided initial support for OpenAPI v3.0.x: https://github.com/ErikWittern/swagger-snippet/pull/17

**Comment by jdillard** [comment]
should this issue be closed now that https://github.com/ErikWittern/swagger-snippet/pull/17 is merged?

**Comment by ErikWittern** [comment]
@jdillard I think so. I will close it for now.
